const strings = {
  en: {
    preview: 'Preview', eyebrow: 'TRY THIS BUILD', title: 'A reader, right here.',
    intro: 'Open a book, turn a page, and try the settings. This preview runs CrossPoint firmware in your browser.',
    back: 'Back', left: '← Left', right: 'Right →', confirm: 'Confirm', pageBack: '↑ Previous page', pageForward: '↓ Next page',
    keyboard: 'Use the buttons or arrow keys · Enter to confirm · Escape to go back. X4 and X3 screens do not support touch.', device: 'Device',
    home: 'Home button', touchHelp: 'Tap to select · Drag or swipe to turn pages · Tap the page center for the menu · ↑ ↓ page buttons · H Home button',
    screenshot: 'Save screenshot', logs: 'Download logs', copy: 'Copy build information',
    diagnostics: 'Diagnostic log', scope: 'For testing reading and menus. Network services, firmware updates, and sleep are not supported. Device memory limits and e-ink refresh behavior are not simulated.',
    credits: 'Browser bridge adapted from', loading: 'Loading firmware…', booting: 'Starting reader…', ready: 'Ready to read',
    error: 'The preview could not start. See the diagnostic log.',
    missing: 'This device has not been built yet.',
    copied: 'Build information copied', copyFailed: 'Could not access the clipboard. Download the logs instead.',
    local: 'local changes', frameTitle: 'CrossPoint reader screen', timeout: 'The reader has not drawn a screen. See the diagnostic log.',
    sdTitle: "Virtual SD card",
    sdIntro: "Add books, fonts, and other files while the reader is running.",
    browseSd: "Browse SD card",
    privacy: "Files stay in this tab. Reloading or clearing the card discards files and settings.",
    dropHint: "Drop files or folders here to upload into",
    restartFirmware: "Restart firmware",
    restartHelp: "Restart keeps your SD card files and saved settings.",
    reset: "Clear SD card",
    resetConfirm: "Clear uploaded files and settings, restore the sample SD card, and restart the preview?",
    sdHelp: "Files are copied immediately. Reopen Browse Files to update its list, or restart firmware to reload fonts and other startup data.",
    fontHelp: "Fonts: upload a family folder into /fonts, for example /fonts/RIDIBatang/*.cpfont. Restart firmware, then choose the family in the reader’s font settings.",
    close: "Close",
    sdRoot: "SD card /",
    uploadFiles: "Upload files",
    uploadFolder: "Upload folder",
    newFolder: "New folder",
    refresh: "Refresh",
    fileName: "Name",
    fileSize: "Size",
    emptyFolder: "This folder is empty.",
    folder: "Folder",
    openFolder: "Open",
    downloadFile: "Download",
    renameFile: "Rename",
    delete: "Delete",
    showHidden: "Show hidden files",
    working: "Working…",
    sdReady: "Ready. Files are saved on the virtual SD card.",
    uploading: "Uploading",
    folderName: "New folder name",
    newName: "New name",
    deleteFile: "Delete this item and everything inside it?",
    replaceFile: "Replace this existing file?",
    fileError: "The file operation failed. Files already uploaded are kept. Refresh the folder and try again.",
    notReady: "The reader is not ready yet.",
    invalidPath: "Use a valid name within the SD card, without . or .. path segments.",
    alreadyExists: "An item with this name already exists.",
    notDirectory: "This path is not a folder.",
    notFile: "Choose a file.",
    invalidFile: "Could not read this file.",
    invalidOperation: "This file operation is unavailable.",
    storageFull: "Uploads are limited to 64 MiB of total SD card contents. Delete some files first.",
    tooManyFiles: "The card supports up to 8,192 entries and 32 folder levels.",
    activeBook: "Close this book in the reader before changing it.",
    activeFont: "Select a different font in the reader before changing this family.",
    fileInUse: "The reader is using this file or folder. Leave the current screen and try again.",
    protectedFile: "Firmware data in /.crosspoint is read-only while the reader is running. You can download it or clear the SD card.",
  },
  ko: {
    preview: '미리보기', eyebrow: '이 빌드 체험하기', title: '브라우저에서 책을 읽어보세요.',
    intro: '책을 열고, 페이지를 넘기고, 설정을 바꿔보세요. CrossPoint 펌웨어가 브라우저에서 실행됩니다.',
    back: '뒤로', left: '← 왼쪽', right: '오른쪽 →', confirm: '확인', pageBack: '↑ 이전 페이지', pageForward: '↓ 다음 페이지',
    keyboard: '아래 버튼이나 방향키로 이동 · Enter로 확인 · Escape로 뒤로 가기. X4·X3 화면은 터치를 지원하지 않습니다.', device: '기기',
    home: '홈 버튼', touchHelp: '화면을 눌러 선택 · 마우스로 끌거나 손가락으로 밀어서 페이지 이동 · 책 중앙을 눌러 메뉴 열기 · ↑ ↓ 페이지 버튼 · H 홈 버튼',
    screenshot: '화면 저장', logs: '로그 다운로드', copy: '빌드 정보 복사',
    diagnostics: '진단 로그', scope: '독서 화면과 메뉴를 테스트할 수 있습니다. 네트워크 서비스, 펌웨어 업데이트, 절전은 지원하지 않습니다. 실기기의 메모리 제한과 전자잉크 갱신 동작은 재현하지 않습니다.',
    credits: '브라우저 연결 코드 원작', loading: '펌웨어를 불러오는 중…', booting: '리더를 시작하는 중…', ready: '읽을 준비가 됐습니다',
    error: '미리보기를 시작하지 못했습니다. 진단 로그를 확인하세요.',
    missing: '이 기기의 미리보기 빌드가 아직 없습니다.',
    copied: '빌드 정보를 복사했습니다', copyFailed: '클립보드에 접근하지 못했습니다. 로그를 다운로드해주세요.',
    local: '로컬 변경 포함', frameTitle: 'CrossPoint 독서 화면', timeout: '리더 화면이 표시되지 않았습니다. 진단 로그를 확인하세요.',
    sdTitle: "가상 SD 카드",
    sdIntro: "리더를 사용하는 중에도 책, 글꼴 등 파일을 추가할 수 있습니다.",
    browseSd: "SD 카드 열기",
    privacy: "파일은 이 탭에만 보관됩니다. 새로고침하거나 카드를 초기화하면 파일과 설정이 지워집니다.",
    dropHint: "파일이나 폴더를 끌어다 놓으면 다음 경로에 추가됩니다:",
    restartFirmware: "펌웨어 재시작",
    restartHelp: "재시작해도 SD 카드의 파일과 저장된 설정은 유지됩니다.",
    reset: "SD 카드 초기화",
    resetConfirm: "추가한 파일과 설정을 지우고 샘플 SD 카드로 미리보기를 다시 시작할까요?",
    sdHelp: "파일은 즉시 복사됩니다. 파일 탐색기를 다시 열면 목록이 갱신됩니다. 글꼴 등 시작할 때 읽는 데이터를 다시 불러오려면 펌웨어를 재시작하세요.",
    fontHelp: "글꼴 폴더를 /fonts에 추가한 뒤 펌웨어를 재시작하고 글꼴 설정에서 선택하세요. 예: /fonts/RIDIBatang/*.cpfont",
    close: "닫기",
    sdRoot: "SD 카드 /",
    uploadFiles: "파일 추가",
    uploadFolder: "폴더 추가",
    newFolder: "새 폴더",
    refresh: "새로고침",
    fileName: "이름",
    fileSize: "크기",
    emptyFolder: "폴더가 비어 있습니다.",
    folder: "폴더",
    openFolder: "열기",
    downloadFile: "다운로드",
    renameFile: "이름 바꾸기",
    delete: "삭제",
    showHidden: "숨김 파일 표시",
    working: "처리 중…",
    sdReady: "준비됐습니다. 파일이 가상 SD 카드에 저장됐습니다.",
    uploading: "파일 추가 중",
    folderName: "새 폴더 이름",
    newName: "새 이름",
    deleteFile: "이 항목과 안에 있는 파일을 모두 삭제할까요?",
    replaceFile: "기존 파일을 덮어쓸까요?",
    fileError: "작업을 완료하지 못했습니다. 이미 추가한 파일은 유지됩니다. 목록을 새로고침한 뒤 다시 시도하세요.",
    notReady: "리더가 아직 준비되지 않았습니다.",
    invalidPath: "SD 카드 안의 올바른 경로를 사용하세요. 경로에 . 또는 .. 항목은 사용할 수 없습니다.",
    alreadyExists: "같은 이름의 항목이 이미 있습니다.",
    notDirectory: "폴더 경로가 아닙니다.",
    notFile: "파일을 선택하세요.",
    invalidFile: "파일을 읽지 못했습니다.",
    invalidOperation: "지원하지 않는 파일 작업입니다.",
    storageFull: "파일을 추가하려면 SD 카드의 전체 용량이 64 MiB 이하여야 합니다. 일부 파일을 삭제하세요.",
    tooManyFiles: "파일과 폴더는 합계 8,192개, 폴더 깊이는 32단계까지 지원합니다.",
    activeBook: "리더에서 이 책을 닫은 뒤 변경하세요.",
    activeFont: "리더에서 다른 글꼴을 선택한 뒤 이 글꼴을 변경하세요.",
    fileInUse: "리더가 이 파일이나 폴더를 사용 중입니다. 현재 화면에서 나간 뒤 다시 시도하세요.",
    protectedFile: "리더가 실행 중일 때 /.crosspoint의 펌웨어 데이터는 읽기만 가능합니다. 다운로드하거나 SD 카드를 초기화할 수 있습니다.",
  },
};
export const locale = navigator.language.startsWith('ko') ? 'ko' : 'en';
export const tr = (key) => strings[locale][key] ?? strings.en[key] ?? key;
